(ns collider.net.render.sounds
  "How render names a sound kind on the wire.")

(def table
  "The sound event and the channel of each sound kind."
  {:player/hurt                   [:entity.player.hurt 7]
   :player/hurt-on-fire           [:entity.player.hurt-on-fire 7]
   :player/hurt-drown             [:entity.player.hurt-drown 7]
   :player/hurt-freeze            [:entity.player.hurt-freeze 7]
   :player/hurt-sweet-berry-bush
   [:entity.player.hurt-sweet-berry-bush 7]
   :player/death                  [:entity.player.death 7]
   :sheep/say                     [:entity.sheep.ambient 6]
   :sheep/step                    [:entity.sheep.step 6]
   :sheep/hurt                    [:entity.sheep.hurt 6]
   :sheep/death                   [:entity.sheep.death 6]
   :sheep/shear                   [:entity.sheep.shear 7]
   :cow/say                       [:entity.cow.ambient 6]
   :cow/step                      [:entity.cow.step 6]
   :cow/hurt                      [:entity.cow.hurt 6]
   :cow/death                     [:entity.cow.death 6]
   :cow/milk                      [:entity.cow.milk 7]
   :cow-moody/say                 [:entity.cow-moody.ambient 6]
   :cow-moody/step                [:entity.cow-moody.step 6]
   :cow-moody/hurt                [:entity.cow-moody.hurt 6]
   :cow-moody/death               [:entity.cow-moody.death 6]
   :mooshroom/milk                [:entity.mooshroom.milk 6]
   :mooshroom/suspicious
   [:entity.mooshroom.suspicious-milk 6]
   :mooshroom/shear               [:entity.mooshroom.shear 7]
   :mooshroom/eat                 [:entity.mooshroom.eat 6]
   :mooshroom/convert             [:entity.mooshroom.convert 6]
   :pig/say                       [:entity.pig.ambient 6]
   :pig/step                      [:entity.pig.step 6]
   :pig/hurt                      [:entity.pig.hurt 6]
   :pig/death                     [:entity.pig.death 6]
   :pig/eat                       [:entity.pig.eat 6]
   :pig-big/say                   [:entity.pig-big.ambient 6]
   :pig-big/hurt                  [:entity.pig-big.hurt 6]
   :pig-big/death                 [:entity.pig-big.death 6]
   :pig-big/eat                   [:entity.pig-big.eat 6]
   :pig-mini/say                  [:entity.pig-mini.ambient 6]
   :pig-mini/hurt                 [:entity.pig-mini.hurt 6]
   :pig-mini/death                [:entity.pig-mini.death 6]
   :pig-mini/eat                  [:entity.pig-mini.eat 6]
   :baby-pig/say                  [:entity.baby-pig.ambient 6]
   :baby-pig/step                 [:entity.baby-pig.step 6]
   :baby-pig/hurt                 [:entity.baby-pig.hurt 6]
   :baby-pig/death                [:entity.baby-pig.death 6]
   :baby-pig/eat                  [:entity.baby-pig.eat 6]
   :rabbit/say                    [:entity.rabbit.ambient 6]
   :rabbit/hurt                   [:entity.rabbit.hurt 6]
   :rabbit/death                  [:entity.rabbit.death 6]
   :rabbit/jump                   [:entity.rabbit.jump 6]
   :armadillo/say                 [:entity.armadillo.ambient 6]
   :armadillo/step                [:entity.armadillo.step 6]
   :armadillo/hurt                [:entity.armadillo.hurt 6]
   :armadillo/hurt-reduced
   [:entity.armadillo.hurt-reduced 6]
   :armadillo/death               [:entity.armadillo.death 6]
   :armadillo/eat                 [:entity.armadillo.eat 6]
   :armadillo/roll                [:entity.armadillo.roll 6]
   :armadillo/land                [:entity.armadillo.land 6]
   :armadillo/unroll-start
   [:entity.armadillo.unroll-start 6]
   :armadillo/unroll-finish
   [:entity.armadillo.unroll-finish 6]
   :armadillo/scute-drop          [:entity.armadillo.scute-drop 6]
   :armadillo/brush               [:entity.armadillo.brush 6]
   :goat/say                      [:entity.goat.ambient 6]
   :goat/step                     [:entity.goat.step 6]
   :goat/hurt                     [:entity.goat.hurt 6]
   :goat/death                    [:entity.goat.death 6]
   :goat/eat                      [:entity.goat.eat 6]
   :goat/milk                     [:entity.goat.milk 7]
   :goat/long-jump                [:entity.goat.long-jump 6]
   :goat/prepare-ram              [:entity.goat.prepare-ram 6]
   :goat/ram-impact               [:entity.goat.ram-impact 6]
   :goat/horn-break               [:entity.goat.horn-break 6]
   :goat-screaming/say            [:entity.goat.screaming.ambient 6]
   :goat-screaming/hurt           [:entity.goat.screaming.hurt 6]
   :goat-screaming/death          [:entity.goat.screaming.death 6]
   :goat-screaming/eat            [:entity.goat.screaming.eat 6]
   :goat-screaming/milk           [:entity.goat.screaming.milk 7]
   :goat-screaming/long-jump
   [:entity.goat.screaming.long-jump 6]
   :goat-screaming/prepare-ram
   [:entity.goat.screaming.prepare-ram 6]
   :goat-screaming/ram-impact
   [:entity.goat.screaming.ram-impact 6]
   :chicken/say                   [:entity.chicken.ambient 6]
   :chicken/step                  [:entity.chicken.step 6]
   :chicken/hurt                  [:entity.chicken.hurt 6]
   :chicken/death                 [:entity.chicken.death 6]
   :chicken/egg                   [:entity.chicken.egg 6]
   :chicken-picky/say             [:entity.chicken-picky.ambient 6]
   :chicken-picky/hurt            [:entity.chicken-picky.hurt 6]
   :chicken-picky/death           [:entity.chicken-picky.death 6]
   :baby-chicken/say              [:entity.baby-chicken.ambient 6]
   :baby-chicken/step             [:entity.baby-chicken.step 6]
   :baby-chicken/hurt             [:entity.baby-chicken.hurt 6]
   :baby-chicken/death            [:entity.baby-chicken.death 6]
   :tnt/primed                    [:entity.tnt.primed 4]
   :snowball/throw                [:entity.snowball.throw 6]
   :egg/throw                     [:entity.egg.throw 7]
   :ender-pearl/throw             [:entity.ender-pearl.throw 6]
   :wind-charge/throw             [:entity.wind-charge.throw 6]
   :wind-charge/burst             [:entity.wind-charge.wind-burst 4]
   :splash-potion/throw           [:entity.splash-potion.throw 7]
   :lingering-potion/throw        [:entity.lingering-potion.throw 6]
   :experience-bottle/throw       [:entity.experience-bottle.throw 6]
   :player/levelup                [:entity.player.levelup 7]
   :player/teleport               [:entity.player.teleport 7]
   :hoe/till                      [:item.hoe.till 4]
   :candle/extinguish             [:block.candle.extinguish 4]
   :eyeblossom/open               [:block.eyeblossom.open 4]
   :eyeblossom/close              [:block.eyeblossom.close 4]
   :eyeblossom/open-long          [:block.eyeblossom.open-long 4]
   :eyeblossom/close-long         [:block.eyeblossom.close-long 4]
   :cake/add-candle               [:block.cake.add-candle 4]
   :cave-vines/pick-berries       [:block.cave-vines.pick-berries 4]
   :big-dripleaf/tilt-down        [:block.big-dripleaf.tilt-down 4]
   :big-dripleaf/tilt-up          [:block.big-dripleaf.tilt-up 4]
   :sweet-berry-bush/pick-berries
   [:block.sweet-berry-bush.pick-berries 4]
   :bottle/fill                   [:item.bottle.fill 4]
   :bottle/empty                  [:item.bottle.empty 4]
   :copper-golem/statue
   [:entity.copper-golem-become-statue 4]
   :axe/strip                     [:item.axe.strip 4]
   :axe/scrape                    [:item.axe.scrape 4]
   :axe/wax-off                   [:item.axe.wax-off 4]
   :dye/use                       [:item.dye.use 4]
   :golden-dandelion/use          [:item.golden-dandelion.use 7]
   :golden-dandelion/unuse        [:item.golden-dandelion.unuse 7]
   :glow-ink/use                  [:item.glow-ink-sac.use 4]
   :ink-sac/use                   [:item.ink-sac.use 4]
   :sign/waxed                    [:block.sign.waxed-interact-fail 4]
   :decorated-pot/insert          [:block.decorated-pot.insert 4]
   :decorated-pot/insert-fail     [:block.decorated-pot.insert-fail 4]
   :shelf/place-item              [:block.shelf.place-item 4]
   :shelf/single-swap             [:block.shelf.single-swap 4]
   :shelf/take-item               [:block.shelf.take-item 4]
   :bookshelf/insert              [:block.chiseled-bookshelf.insert 4]
   :bookshelf/insert-enchanted
   [:block.chiseled-bookshelf.insert.enchanted 4]
   :bookshelf/pickup              [:block.chiseled-bookshelf.pickup 4]
   :bookshelf/pickup-enchanted
   [:block.chiseled-bookshelf.pickup.enchanted 4]
   :bell/use                      [:block.bell.use 4]
   :bucket/empty                  [:item.bucket.empty 4]
   :bucket/fill                   [:item.bucket.fill 4]
   :bucket/empty-lava             [:item.bucket.empty-lava 4]
   :bucket/fill-lava              [:item.bucket.fill-lava 4]
   :bucket/empty-snow             [:item.bucket.empty-powder-snow 4]
   :bucket/fill-snow              [:item.bucket.fill-powder-snow 4]
   :pumpkin/carve                 [:block.pumpkin.carve 4]
   :composter/ready               [:block.composter.ready 4]
   :composter/empty               [:block.composter.empty 4]
   :shovel/flatten                [:item.shovel.flatten 4]
   :fire/ignite                   [:item.flintandsteel.use 4]
   :firecharge/use                [:item.firecharge.use 4]
   :generic/extinguish-fire       [:entity.generic.extinguish-fire 4]
   :wet-sponge/dries              [:block.wet-sponge.dries 4]
   :generic/burn                  [:entity.generic.burn 8]
   :explosion                     [:entity.generic.explode 4]
   :splash                        [:entity.generic.splash 6]
   :swim                          [:entity.generic.swim 6]})
