(ns collider.world.direction)

(set! *warn-on-reflection* true)

(def six [:down :up :north :south :west :east])
(def horizontal [:north :south :west :east])
(def offset {:down [0 -1 0] :up [0 1 0] :north [0 0 -1] :south [0 0 1] :west [-1 0 0] :east [1 0 0]})
(def horizontal-offset {:north [0 0 -1] :south [0 0 1] :west [-1 0 0] :east [1 0 0]})
(def around (mapv offset [:east :west :up :down :south :north]))
(def opposite {:down :up :up :down :north :south :south :north :west :east :east :west})
(def clockwise {:north :east :east :south :south :west :west :north})
(def counter-clockwise {:north :west :west :south :south :east :east :north})
(def axis {:down :y :up :y :north :z :south :z :west :x :east :x})
(def index {:down 0 :up 1 :north 2 :south 3 :west 4 :east 5})
(def from-index (zipmap (range) six))
(def face-offset (zipmap (range) (mapv offset six)))
(def face-facing {2 :north 3 :south 4 :west 5 :east})
(def opposite-index (int-array [1 0 3 2 5 4]))
(def ^:private player-order [:south :west :north :east])
(defn player-index ^long [yaw]
  (bit-and (long (Math/floor (+ (/ (* (double yaw) 4.0) 360.0) 0.5))) 3))
(defn player-direction [yaw] (nth player-order (player-index yaw)))
(defn up [p] (mapv + p [0 1 0]))
(defn down [p] (mapv + p [0 -1 0]))
